language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - 7.0

matrix:
    allow_failures:
        - php: hhvm
        - php: 7.0

before_script:
  - bash -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then phpenv config-add travis.php.ini; fi;'
  - mysql -u root -e "CREATE DATABASE basercms CHARACTER SET utf8;"
  - mysql -u root -e "GRANT ALL PRIVILEGES ON basercms.* TO basercms@localhost IDENTIFIED BY 'basercms'"
  - mysql -u basercms --password="basercms" -e "SHOW DATABASES;"
  - composer install --dev
  - cd app
  - php ./Console/cake.php bc_manager checkenv
  - php ./Console/cake.php bc_manager install "http://localhost" "mysql" "admin" "basercms" "webmaster@example.org" --host "localhost" --database "basercms" --login "basercms" --password "basercms" --prefix "mysite_"  --port "3306"  --smarturl "true"  --data "nada-icons.default"

script:
  - php ./Console/cake.php baser_test baser BcAll

notifications:
  email: false